[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15

startup_mode =  "Maximized" # "Fullscreen" #"Windowed" # "Maximized"
decorations = "None"
opacity = 0.85
blur = true
dynamic_title = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
bold.family = "MesloLGS Nerd Font Mono"
italic.family = "MesloLGS Nerd Font Mono"
bold_italic.family = "MesloLGS Nerd Font Mono"
offset.x = 0
offset.y = 1
size = 13

[general]
import = [
    "~/.config/alacritty/gnome_terminal.toml"
]

[terminal.shell] 
program = "/bin/bash"

[cursor]
style.shape = "Underline"
style.blinking = "Always"
blink_interval = 500

[colors]
draw_bold_text_with_bright_colors = true
