format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$docker_context\
$jobs\
$cmd_duration \
$username\
$hostname\
$line_break\
$character"""

palette = "gnome"

[fill]
symbol = '—'
style = 'grey'

[directory]
style = 'bold fg:blue'
format = '[  $path ]($style)'
truncation_length = 3
truncation_symbol = '󰇘/'
truncate_to_repo = false

[git_branch]
style = 'fg:green'
symbol = ''
format = '[on](white) [$symbol $branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 500
style = 'fg:grey'
format = '[ $duration]($style)'

[palettes.gnome]
grey = "#5A5A5A"

[docker_context]
symbol = ' '
style = 'fg:light_blue'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[username]
format = '[$user@]($style)'
style_user = 'bold yellow'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname $ssh_symbol]($style)'
style = 'bold yellow'
